[package]
name = "redstone-computer-utilities"
version = "0.3.0"
edition = "2024"

[dependencies]
log = "0.4"
tungstenite = "0.27"
macros = { path = "./macros" }
thiserror = "2.0"
percent-encoding = "2.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
